// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:66cf0991-ebc2-4958-9fc6-74730c25e711",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YSp7RX6Ui",
    "aws_user_pools_web_client_id": "5vdjjbo8mkohmcfa9ht72up98f",
    "oauth": {},
    "aws_user_files_s3_bucket": "notes-env",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_content_delivery_bucket": "emmaapp-20191019133150-hostingbucket-env",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://emmaapp-20191019133150-hostingbucket-env.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
